# Generated by Django 5.0.14 on 2026-08-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_avis_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='groupe_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
