# Generated by Django 5.0.14 on 2026-08-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_groupe_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
