# Generated by Django 5.0.14 on 2026-08-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_avis_statut_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_suppression_demandee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
