from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('terrains/', views.liste_terrains, name='terrains'),
    path('terrains/<int:pk>/', views.detail_terrain, name='terrain_detail'),
    path('inscription/', views.inscription, name='inscription'),
    path('connexion/', views.connexion, name='connexion'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    path('tableau-de-bord/', views.dashboard, name='dashboard'),
    path('reserver/<int:creneau_id>/', views.reserver, name='reserver'),
    path('reserver/', views.reserver_multi, name='reserver_multi'),
    path('profil/', views.profil, name='profil'),
    path('supprimer-compte/', views.supprimer_compte, name='supprimer_compte'),
    path('paiement/creer/<int:creneau_id>/', views.creer_paiement, name='creer_paiement'),
    path('paiement/creer/', views.creer_paiement, name='creer_paiement_multi'),
    path('paiement/succes/', views.paiement_succes, name='paiement_succes'),
    path('reservations/<int:reservation_id>/annuler/', views.annuler_reservation, name='annuler_reservation'),
    path('reservations/<int:reservation_id>/modifier/', views.modifier_reservation, name='modifier_reservation'),
    path('reservation/', views.calendrier, name='calendrier'),
    path('conditions-utilisation/', views.conditions, name='conditions'),
    path('confidentialite/', views.confidentialite, name='confidentialite'),
    path('nos-complexes/', views.nos_complexes, name='nos_complexes'),
    path('contact/', views.contact, name='contact'),
    path('admin-sportify/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-sportify/utilisateurs/', views.admin_utilisateurs, name='admin_utilisateurs'),
    path('admin-sportify/avis/', views.admin_avis, name='admin_avis'),
    path('admin-sportify/avis/<int:avis_id>/moderer/', views.moderer_avis, name='moderer_avis'),
    path('admin-sportify/utilisateurs/<int:user_id>/bloquer/', views.bloquer_utilisateur, name='bloquer_utilisateur'),
    path('api/creneaux/', views.api_creneaux, name='api_creneaux'),
    path('reservations/<int:reservation_id>/facture/', views.telecharger_facture, name='telecharger_facture'),
    path('reservations/<int:reservation_id>/calendrier/', views.telecharger_ics, name='telecharger_ics'),
    path('terrains/<int:terrain_id>/avis/', views.donner_avis, name='donner_avis'),
]
